services:
  app:
    build: app
    depends_on:
      - db
    environment:
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "3000:3000"

  db:
    image: postgres:18.0
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: db
    expose:
      - "5432"
    volumes:
      - db:/var/lib/postgresql
      - ./db:/docker-entrypoint-initdb.d

volumes:
  db:
