FROM ruby:3.4.6-slim

WORKDIR /rails

ENV RAILS_ENV="development"

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y curl libjemalloc2 libvips build-essential git libyaml-dev pkg-config && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

COPY . .

RUN ["bundle", "install"]

ENTRYPOINT ["/rails/bin/docker-entrypoint.dev"]
